apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: v11j4zjq9-nodejs 
  janus-idp.io/tekton: v11j4zjq9-nodejs
  backstage.io/kubernetes-id: v11j4zjq9-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: v11j4zjq9-nodejs
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml